# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Parser_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 251)
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        MainWindow.setAcceptDrops(False)
        MainWindow.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(57, 0, 60, 255), stop:1 rgba(86, 173, 139, 255));\n"
"")
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Terminal_TextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Terminal_TextEdit.setGeometry(QtCore.QRect(400, 10, 391, 231))
        self.Terminal_TextEdit.setStyleSheet("background-color: rgba(0, 0, 0, 103);\n"
"border_radius: 15;\n"
"color: rgb(255, 255, 255);")
        self.Terminal_TextEdit.setReadOnly(True)
        self.Terminal_TextEdit.setObjectName("Terminal_TextEdit")
        self.Adres_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Adres_lineEdit.setGeometry(QtCore.QRect(10, 60, 311, 31))
        self.Adres_lineEdit.setStyleSheet("background-color: rgba(0, 0, 0, 103);\n"
"color: rgb(253, 250, 255);\n"
"border-radius: 13;\n"
"border-color: rgb(255, 255, 255);")
        self.Adres_lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.Adres_lineEdit.setCursorPosition(0)
        self.Adres_lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Adres_lineEdit.setReadOnly(True)
        self.Adres_lineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.Adres_lineEdit.setObjectName("Adres_lineEdit")
        self.Copy_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Copy_Button.setGeometry(QtCore.QRect(330, 60, 61, 31))
        self.Copy_Button.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0.497537, y1:0, x2:0.497537, y2:1, stop:0 rgba(53, 147, 238, 255), stop:1 rgba(44, 77, 184, 255));\n"
"border-radius: 13;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: qlineargradient(spread:reflect, x1:0.497537, y1:0, x2:0.497537, y2:1, stop:0 rgba(48, 134, 218, 255), stop:1 rgba(44, 77, 184, 255));\n"
"border-radius: 13;\n"
"}")
        self.Copy_Button.setObjectName("Copy_Button")
        self.Adres_label = QtWidgets.QLabel(self.centralwidget)
        self.Adres_label.setGeometry(QtCore.QRect(110, 40, 151, 16))
        self.Adres_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.Adres_label.setObjectName("Adres_label")
        self.Parse_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Parse_Button.setEnabled(True)
        self.Parse_Button.setGeometry(QtCore.QRect(220, 160, 81, 32))
        self.Parse_Button.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0.497537, y1:0, x2:0.497537, y2:1, stop:0 rgba(53, 147, 238, 255), stop:1 rgba(44, 77, 184, 255));\n"
"border-radius: 13\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: qlineargradient(spread:reflect, x1:0.497537, y1:0, x2:0.497537, y2:1, stop:0 rgba(48, 134, 218, 255), stop:1 rgba(44, 77, 184, 255));\n"
"border-radius: 13\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: qlineargradient(spread:reflect, x1:0.497537, y1:0, x2:0.497537, y2:1, stop:0 rgba(48, 134, 218, 255), stop:1 rgba(44, 77, 184, 255));\n"
"color: black;\n"
"border-radius: 13\n"
"}")
        self.Parse_Button.setObjectName("Parse_Button")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(160, 120, 201, 21))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"background-color: rgb(184, 184, 184);\n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"border-radius: 10;\n"
"color: black;\n"
"}\n"
"\n"
"QProgressBar:chunk{\n"
"border-radius: 10;\n"
"    background-color: qlineargradient(spread:reflect, x1:0.497537, y1:0, x2:0.497537, y2:1, stop:0 rgba(48, 134, 218, 255), stop:1 rgba(44, 77, 184, 255));\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.checkBox_USDT = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_USDT.setGeometry(QtCore.QRect(40, 140, 61, 16))
        self.checkBox_USDT.setTabletTracking(True)
        self.checkBox_USDT.setAcceptDrops(False)
        self.checkBox_USDT.setAutoFillBackground(False)
        self.checkBox_USDT.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.568318, y1:1, x2:0.591, y2:0, stop:0.147727 rgba(160, 146, 146, 0), stop:1 rgba(193, 203, 199, 0));\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.checkBox_USDT.setChecked(True)
        self.checkBox_USDT.setAutoRepeat(False)
        self.checkBox_USDT.setObjectName("checkBox_USDT")
        self.checkBox_BTC = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_BTC.setGeometry(QtCore.QRect(40, 160, 61, 16))
        self.checkBox_BTC.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.568318, y1:1, x2:0.591, y2:0, stop:0.147727 rgba(160, 146, 146, 0), stop:1 rgba(193, 203, 199, 0));\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"gridline-color: rgb(39, 71, 255);")
        self.checkBox_BTC.setChecked(True)
        self.checkBox_BTC.setObjectName("checkBox_BTC")
        self.Close_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Close_Button.setGeometry(QtCore.QRect(10, 10, 16, 16))
        self.Close_Button.setStyleSheet("QPushButton{\n"
"color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(57, 0, 60, 0), stop:1 rgba(86, 173, 139, 0));\n"
"border-radius: 7.5;\n"
"background-color: qlineargradient(spread:reflect, x1:0.497537, y1:0, x2:0.497537, y2:1, stop:0 rgba(207, 33, 0, 255), stop:1 rgba(153, 44, 0, 255));\n"
"}\n"
"QPushButton:hover{\n"
"color: black;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: qlineargradient(spread:reflect, x1:0.497537, y1:0, x2:0.497537, y2:1, stop:0 rgba(176, 28, 0, 255), stop:1 rgba(153, 44, 0, 255));\n"
"}")
        self.Close_Button.setObjectName("Close_Button")
        self.Minimized_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Minimized_Button.setGeometry(QtCore.QRect(40, 10, 16, 16))
        self.Minimized_Button.setStyleSheet("QPushButton{\n"
"font: 18pt \".AppleSystemUIFont\";\n"
"color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(57, 0, 60, 0), stop:1 rgba(86, 173, 139, 0));\n"
"border-radius: 7.5;\n"
"background-color: qlineargradient(spread:reflect, x1:0.497537, y1:0, x2:0.497537, y2:1, stop:0 rgba(207, 168, 0, 255), stop:1 rgba(153, 102, 0, 255));\n"
"}\n"
"QPushButton:hover{\n"
"color: black;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: qlineargradient(spread:reflect, x1:0.497537, y1:0, x2:0.497537, y2:1, stop:0 rgba(170, 139, 0, 255), stop:1 rgba(153, 102, 0, 255));\n"
"}")
        self.Minimized_Button.setObjectName("Minimized_Button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 120, 31, 16))
        self.label.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(57, 0, 60, 0), stop:1 rgba(86, 173, 139, 0));\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Close_Button.clicked.connect(MainWindow.close) # type: ignore
        self.Minimized_Button.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Adres_lineEdit.setText(_translate("MainWindow", "https://docs.google.com/spreadsheets/d/1AA34T69zhsKM7dX3FqonW1v6SbLODFtHqF4tNoiyK_U/edit#gid=0"))
        self.Copy_Button.setText(_translate("MainWindow", "Copy"))
        self.Adres_label.setText(_translate("MainWindow", "Адрес Google-таблицы"))
        self.Parse_Button.setText(_translate("MainWindow", "Parse"))
        self.checkBox_USDT.setText(_translate("MainWindow", "USDT"))
        self.checkBox_BTC.setText(_translate("MainWindow", "BTC"))
        self.Close_Button.setText(_translate("MainWindow", "X"))
        self.Minimized_Button.setText(_translate("MainWindow", "-"))
        self.label.setText(_translate("MainWindow", "Fiat"))
